apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  name: resnet50v1-5-fp32-training
spec:
  mpiReplicaSpecs:
    Launcher:
      template:
        spec:
          containers:
          - name: mpi-launcher
            image: $(REGISTRY)/model-zoo:2.1.0-image-recognition-resnet50v1-5-fp32-training
            imagePullPolicy: Always
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              fsGroup: 0
            envFrom:
            - configMapRef:
                name: mlops-env
            workingDir: /
            command:
            - $(MODEL_DIR)/examples/fp32_training_multi_node.sh
            volumeMounts:
            - name: datasets
              mountPath: $(DATASET_DIR)
              readOnly: true
            - name: users
              mountPath: /Users
    Worker:
      template:
        spec:
          containers:
          - name: mpi-worker
            image: $(REGISTRY)/model-zoo:2.1.0-image-recognition-resnet50v1-5-fp32-training
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              fsGroup: 0
            envFrom:
            - configMapRef:
                name: mlops-env
            workingDir: /
            volumeMounts:
            - name: datasets
              mountPath: $(DATASET_DIR)
              readOnly: true
            - name: users
              mountPath: /Users
