releases:
  versioned:
    tag_specs:
    - '{_TAG_PREFIX}{intel-tf}{language-modeling}{bert-large-fp32-inference}'
slice_sets:
  bert-large-fp32-inference:
  - add_to_name: -bert-large-fp32-inference
    args:
    - TENSORFLOW_IMAGE=intel/intel-optimized-tensorflow
    - PACKAGE_NAME=bert-large-fp32-inference
    dockerfile_subdirectory: model_containers
    files:
    - destination: benchmarks/common
      source: benchmarks/common
    - destination: benchmarks/language_modeling/tensorflow/bert_large/README.md
      source: benchmarks/language_modeling/tensorflow/bert_large/README.md
    - destination: benchmarks/language_modeling/tensorflow/bert_large/__init__.py
      source: benchmarks/language_modeling/tensorflow/bert_large/__init__.py
    - destination: benchmarks/language_modeling/tensorflow/bert_large/inference/__init__.py
      source: benchmarks/language_modeling/tensorflow/bert_large/inference/__init__.py
    - destination: benchmarks/language_modeling/tensorflow/bert_large/inference/fp32
      source: benchmarks/language_modeling/tensorflow/bert_large/inference/fp32
    - destination: benchmarks/launch_benchmark.py
      source: benchmarks/launch_benchmark.py
    - destination: models/common
      source: models/common
    - destination: models/language_modeling/tensorflow/bert_large/inference
      source: models/language_modeling/tensorflow/bert_large/inference
    - destination: quickstart/common
      source: quickstart/common
    - destination: quickstart
      source: quickstart/language_modeling/tensorflow/bert_large/inference/cpu/fp32
    downloads:
      - source: https://storage.googleapis.com/intel-optimized-tensorflow/models/v1_6_1/bert_large_checkpoints.zip
        destination: pretrained_model/bert_large_checkpoints.zip
      - source: https://storage.googleapis.com/intel-optimized-tensorflow/models/v2_4_0/fp32_bert_squad.pb
        destination: pretrained_model/fp32_bert_squad.pb
    partials:
    - model_package
    - unzip
    - entrypoint
    documentation:
      name: README.md
      uri: models/quickstart/language_modeling/tensorflow/bert_large/inference/cpu/fp32
      text_replace:
        <mode>: inference
        <model name>: BERT Large
        <precision>: FP32
        <use case>: language_modeling
        <package url>: https://storage.googleapis.com/intel-optimized-tensorflow/models/v2_3_0/bert-large-fp32-inference.tar.gz
        <package name>: bert-large-fp32-inference.tar.gz
        <package dir>: bert-large-fp32-inference
        <docker image>: intel/language-modeling:tf-2.4.0-bert-large-fp32-inference
      docs:
      - name: Title
        uri: models/quickstart/language_modeling/tensorflow/bert_large/inference/cpu/fp32/.docs/title.md
      - name: Description
        uri: models/quickstart/language_modeling/tensorflow/bert_large/inference/cpu/fp32/.docs/description.md
      - name: Download link
        uri: models/quickstart/language_modeling/tensorflow/bert_large/inference/cpu/fp32/.docs/download.md
      - name: Datasets
        uri: models/quickstart/language_modeling/tensorflow/bert_large/inference/cpu/fp32/.docs/datasets.md
      - name: Quick Start Scripts
        uri: models/quickstart/language_modeling/tensorflow/bert_large/inference/cpu/fp32/.docs/quickstart.md
      - name: Bare Metal
        uri: models/quickstart/language_modeling/tensorflow/bert_large/inference/cpu/fp32/.docs/baremetal.md
      - name: Docker
        uri: models/quickstart/language_modeling/tensorflow/bert_large/inference/cpu/fp32/.docs/docker.md
      - name: License link
        uri: models/quickstart/image_recognition/tensorflow/resnet50v1_5/training/cpu/fp32/.docs/license.md
