releases:
  versioned:
    tag_specs:
    - '{_TAG_PREFIX}{intel-tf}{language-translation}{bert-fp32-inference}'
slice_sets:
  bert-fp32-inference:
  - add_to_name: -bert-fp32-inference
    args:
    - PACKAGE_NAME=bert-fp32-inference
    dockerfile_subdirectory: model_containers
    downloads:
    - source: https://storage.googleapis.com/bert_models/2018_10_18/uncased_L-12_H-768_A-12.zip
      destination: uncased_L-12_H-768_A-12.zip
    files:
    - destination: benchmarks/common
      source: benchmarks/common
    - destination: benchmarks/language_translation/__init__.py
      source: benchmarks/language_translation/__init__.py
    - destination: benchmarks/language_translation/tensorflow/__init__.py
      source: benchmarks/language_translation/tensorflow/__init__.py
    - destination: benchmarks/language_translation/tensorflow/bert/__init__.py
      source: benchmarks/language_translation/tensorflow/bert/__init__.py
    - destination: benchmarks/language_translation/tensorflow/bert/inference/fp32
      source: benchmarks/language_translation/tensorflow/bert/inference/fp32
    - destination: benchmarks/launch_benchmark.py
      source: benchmarks/launch_benchmark.py
    - destination: models/common
      source: models/common
    - destination: models/language_translation/tensorflow/bert/inference/fp32
      source: models/language_translation/tensorflow/bert/inference/fp32
    - destination: quickstart/common
      source: quickstart/common
    - destination: quickstart
      source: quickstart/language_translation/tensorflow/bert/inference/cpu/fp32
    partials:
    - model_package
    documentation:
      - docs:
        - name: Title
          uri: models/quickstart/language_translation/tensorflow/bert/inference/cpu/.docs/title.md
        - name: Description
          uri: models/quickstart/language_translation/tensorflow/bert/inference/cpu/.docs/description.md
        - name: Datasets
          uri: models/quickstart/language_translation/tensorflow/bert/inference/cpu/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/language_translation/tensorflow/bert/inference/cpu/.docs/quickstart.md
        - name: AI Kit
          uri: models/quickstart/language_translation/tensorflow/bert/inference/cpu/.docs/aikit.md
        name: README.md
        text_replace:
          <mode>: inference
          <model name>: BERT
          <precision>: FP32
          <use case>: language_translation
        uri: models/benchmarks/language_translation/tensorflow/bert/inference/fp32
