releases:
    versioned:
        tag_specs:
            - "{_TAG_PREFIX}{intel-tf}{image-recognition}{resnet50-fp32-inference}"
slice_sets:
    resnet50-fp32-inference:
        - add_to_name: "-resnet50-fp32-inference"
          dockerfile_subdirectory: "model_containers"
          partials:
              - model_package
              - entrypoint
          documentation:
            - name: README.md
              uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/cpu/fp32
              text_replace:
                <model name>: ResNet50
                <precision>: FP32
                <mode>: inference
                <use case>: image_recognition
                <package url>: https://storage.googleapis.com/intel-optimized-tensorflow/models/v2_7_0/resnet50-fp32-inference.tar.gz
                <package name>: resnet50-fp32-inference.tar.gz
                <package dir>: resnet50-fp32-inference
                <docker image>: intel/image-recognition:tf-latest-resnet50-fp32-inference
              docs:
              - name: Title
                uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/cpu/fp32/.docs/title.md
              - name: Description
                uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/cpu/fp32/.docs/description.md
              - name: Download link
                uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/cpu/fp32/.docs/download.md
              - name: Datasets
                uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/cpu/int8/.docs/datasets.md
              - name: Quick Start Scripts
                uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/cpu/fp32/.docs/quickstart.md
              - name: Bare Metal
                uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/cpu/fp32/.docs/baremetal.md
              - name: Docker
                uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/cpu/fp32/.docs/docker.md
              - name: Advanced Options
                uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/cpu/fp32/.docs/advancedoptions.md
              - name: License link
                uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/cpu/fp32/.docs/license.md
            - docs:
              - name: Title
                uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/cpu/fp32/.docs/title.md
              - name: Description
                uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/cpu/fp32/.docs/description.md
              - name: Datasets
                uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/cpu/fp32/.docs/datasets.md
              - name: Quick Start Scripts
                uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/cpu/fp32/.docs/quickstart.md
              - name: AI Kit
                uri: models/quickstart/image_recognition/tensorflow/resnet50/inference/cpu/fp32/.docs/aikit.md
              - name: Resources
                uri: models/quickstart/common/.docs/resources_with_portal_link.md
              name: README.md
              text_replace:
                <mode>: inference
                <model name>: ResNet50
                <precision>: FP32
                <use case>: image_recognition
                <workload container url>: https://software.intel.com/content/www/us/en/develop/articles/containers/resnet50-fp32-inference-tensorflow-container.html
              uri: models/benchmarks/image_recognition/tensorflow/resnet50/inference/fp32
            - docs:
              - name: Title
                uri: models/quickstart/common/.docs/advanced/title.md
              - name: Description
                uri: models/quickstart/common/.docs/advanced/description.md
              - name: Setup
                uri: models/quickstart/common/.docs/advanced/setup.md
              - name: Docker arg
                uri: models/quickstart/common/.docs/advanced/docker_arg.md
              - name: Launch benchmark instructions
                uri: models/benchmarks/image_recognition/tensorflow/resnet50/inference/fp32/.docs/advanced/launch_benchmark_instructions.md
              name: Advanced.md
              text_replace:
                <mode>: inference
                <model name>: ResNet50 V1
                <precision>: FP32
                <use case>: image_recognition
                <docker image>: intel/intel-optimized-tensorflow:latest
              uri: models/benchmarks/image_recognition/tensorflow/resnet50/inference/fp32
          args:
              - PACKAGE_NAME=resnet50-fp32-inference
          files:
              - source: benchmarks/common
                destination: benchmarks/common
              - source: benchmarks/launch_benchmark.py
                destination: benchmarks/launch_benchmark.py
              - source: benchmarks/image_recognition/tensorflow/resnet50/inference/fp32
                destination: benchmarks/image_recognition/tensorflow/resnet50/inference/fp32
              - source: benchmarks/image_recognition/__init__.py
                destination: benchmarks/image_recognition/__init__.py
              - source: benchmarks/image_recognition/tensorflow/__init__.py
                destination: benchmarks/image_recognition/tensorflow/__init__.py
              - source: benchmarks/image_recognition/tensorflow/resnet50/__init__.py
                destination: benchmarks/image_recognition/tensorflow/resnet50/__init__.py
              - source: benchmarks/image_recognition/tensorflow/resnet50/inference/__init__.py
                destination: benchmarks/image_recognition/tensorflow/resnet50/inference/__init__.py
              - source: benchmarks/image_recognition/tensorflow/resnet50/inference/fp32/__init__.py
                destination: benchmarks/image_recognition/tensorflow/resnet50/inference/fp32/__init__.py
              - source: benchmarks/image_recognition/tensorflow/resnet50/README.md
                destination: benchmarks/image_recognition/tensorflow/resnet50/README.md
              - source: models/image_recognition/tensorflow/resnet50/inference
                destination: models/image_recognition/tensorflow/resnet50/inference
              - destination: quickstart/common
                source: quickstart/common
              - source: quickstart/image_recognition/tensorflow/resnet50/inference/cpu/fp32
                destination: quickstart
          downloads:
              - source: https://storage.googleapis.com/intel-optimized-tensorflow/models/v1_6/resnet50_fp32_pretrained_model.pb
                destination: resnet50_fp32_pretrained_model.pb
