releases:
  versioned:
    tag_specs:
    - '{_TAG_PREFIX}{intel-tf}{object-detection}{ssd-mobilenet-fp32-inference}'
slice_sets:
  ssd-mobilenet-fp32-inference:
  - add_to_name: -ssd-mobilenet-fp32-inference
    args:
    - TENSORFLOW_IMAGE=intel/intel-optimized-tensorflow
    - PACKAGE_NAME=ssd-mobilenet-fp32-inference
    dockerfile_subdirectory: model_containers
    downloads:
    - source: https://storage.googleapis.com/intel-optimized-tensorflow/models/ssdmobilenet_fp32_pretrained_model_combinedNMS.pb
      destination: pretrained_model/ssdmobilenet_fp32_pretrained_model_combinedNMS.pb
    files:
    - destination: benchmarks/common
      source: benchmarks/common
    - destination: benchmarks/launch_benchmark.py
      source: benchmarks/launch_benchmark.py
    - destination: benchmarks/object_detection/__init__.py
      source: benchmarks/object_detection/__init__.py
    - destination: benchmarks/object_detection/tensorflow/__init__.py
      source: benchmarks/object_detection/tensorflow/__init__.py
    - destination: benchmarks/object_detection/tensorflow/ssd-mobilenet/README.md
      source: benchmarks/object_detection/tensorflow/ssd-mobilenet/README.md
    - destination: benchmarks/object_detection/tensorflow/ssd-mobilenet/__init__.py
      source: benchmarks/object_detection/tensorflow/ssd-mobilenet/__init__.py
    - destination: benchmarks/object_detection/tensorflow/ssd-mobilenet/inference/__init__.py
      source: benchmarks/object_detection/tensorflow/ssd-mobilenet/inference/__init__.py
    - destination: benchmarks/object_detection/tensorflow/ssd-mobilenet/inference/fp32
      source: benchmarks/object_detection/tensorflow/ssd-mobilenet/inference/fp32
    - destination: models/common
      source: models/common
    - destination: models/object_detection/tensorflow/ssd-mobilenet/inference
      source: models/object_detection/tensorflow/ssd-mobilenet/inference
    - destination: models/object_detection/tensorflow/ssd-mobilenet/inference/__init__.py
      source: models/object_detection/tensorflow/ssd-mobilenet/inference/__init__.py
    - destination: models/object_detection/tensorflow/ssd-mobilenet/inference/coco_detection_evaluator.py
      source: models/object_detection/tensorflow/ssd-mobilenet/inference/coco_detection_evaluator.py
    - destination: models/object_detection/tensorflow/ssd-mobilenet/inference/coco_label_map.py
      source: models/object_detection/tensorflow/ssd-mobilenet/inference/coco_label_map.py
    - destination: models/object_detection/tensorflow/ssd-mobilenet/inference/coco_tools.py
      source: models/object_detection/tensorflow/ssd-mobilenet/inference/coco_tools.py
    - destination: models/object_detection/tensorflow/ssd-mobilenet/inference/ssdmobilenet_preprocess.pb
      source: models/object_detection/tensorflow/ssd-mobilenet/inference/ssdmobilenet_preprocess.pb
    - destination: quickstart/common
      source: quickstart/common
    - destination: quickstart
      source: quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/fp32
    partials:
    - numactl
    - model_package
    - entrypoint
    documentation:
      - name: README.md
        uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/fp32
        text_replace:
          <model name>: SSD-MobileNet
          <precision>: FP32
          <mode>: inference
          <use case>: object_detection
          <package url>: https://storage.googleapis.com/intel-optimized-tensorflow/models/v2_7_0/ssd-mobilenet-fp32-inference.tar.gz
          <package name>: ssd-mobilenet-fp32-inference.tar.gz
          <package dir>: ssd-mobilenet-fp32-inference
          <docker image>: intel/object-detection:tf-latest-ssd-mobilenet-fp32-inference
        docs:
        - name: Title
          uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/fp32/.docs/title.md
        - name: Description
          uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/fp32/.docs/description.md
        - name: Download link
          uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/fp32/.docs/download.md
        - name: Datasets
          uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/fp32/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/fp32/.docs/quickstart.md
        - name: Bare Metal
          uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/fp32/.docs/baremetal.md
        - name: Docker
          uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/fp32/.docs/docker.md
        - name: License link
          uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/fp32/.docs/license.md
      - name: README.md
        uri: models/benchmarks/object_detection/tensorflow/ssd-mobilenet/inference/fp32
        text_replace:
          <model name>: SSD-MobileNet
          <precision>: FP32
          <mode>: inference
          <use case>: object_detection
          <workload container url>: https://software.intel.com/content/www/us/en/develop/articles/containers/ssd-mobilenet-fp32-inference-tensorflow-container.html
        docs:
        - name: Title
          uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/fp32/.docs/title.md
        - name: Description
          uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/fp32/.docs/description.md
        - name: Datasets
          uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/fp32/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/fp32/.docs/quickstart.md
        - name: AI Kit
          uri: models/quickstart/object_detection/tensorflow/ssd-mobilenet/inference/cpu/fp32/.docs/aikit.md
        - name: Resources
          uri: models/quickstart/common/.docs/resources_with_portal_link.md
      - docs:
        - name: Title
          uri: models/quickstart/common/.docs/advanced/title.md
        - name: Description
          uri: models/quickstart/common/.docs/advanced/description.md
        - name: Setup
          uri: models/quickstart/common/.docs/advanced/setup.md
        - name: Docker arg
          uri: models/quickstart/common/.docs/advanced/docker_arg.md
        - name: Launch benchmark instructions
          uri: models/benchmarks/object_detection/tensorflow/ssd-mobilenet/inference/fp32/.docs/advanced/launch_benchmark_instructions.md
        name: Advanced.md
        text_replace:
          <model name>: SSD-MobileNet
          <precision>: FP32
          <mode>: inference
          <use case>: object_detection
          <docker image>: 'intel/intel-optimized-tensorflow:latest'
        uri: models/benchmarks/object_detection/tensorflow/ssd-mobilenet/inference/fp32
