releases:
  versioned:
    tag_specs:
      - "{tensorflow-itex-flex-series-base-public}{tf-flex-series-ssd-mobilenet-inference}"
slice_sets:
  tf-flex-series-ssd-mobilenet-inference:
    - add_to_name: -tf-flex-series-ssd-mobilenet-inference
      dockerfile_exclusive_name: -ssd-mobilenet-inference
      args:
        - PACKAGE_NAME=tf-flex-series-ssd-mobilenet-inference
      dockerfile_subdirectory: gpu_model_containers
      downloads:
        - destination: pretrained_models/ssdmobilenet_int8_pretrained_model_gpu.pb
          source: https://storage.googleapis.com/intel-optimized-tensorflow/models/gpu/ssd_mobilenet_v1_int8_itex.pb
      files:
        - destination: benchmarks/common
          source: benchmarks/common
        - destination: benchmarks/launch_benchmark.py
          source: benchmarks/launch_benchmark.py
        - destination: benchmarks/object_detection/__init__.py
          source: benchmarks/object_detection/__init__.py
        - destination: benchmarks/object_detection/tensorflow/__init__.py
          source: benchmarks/object_detection/tensorflow/__init__.py
        - destination: benchmarks/object_detection/tensorflow/ssd-mobilenet/__init__.py
          source: benchmarks/object_detection/tensorflow/ssd-mobilenet/__init__.py
        - destination: benchmarks/object_detection/tensorflow/ssd-mobilenet/inference/__init__.py
          source: benchmarks/object_detection/tensorflow/ssd-mobilenet/inference/__init__.py
        - destination: benchmarks/object_detection/tensorflow/ssd-mobilenet/inference/int8
          source: benchmarks/object_detection/tensorflow/ssd-mobilenet/inference/int8
        - destination: models/object_detection/tensorflow/ssd-mobilenet/inference/__init__.py
          source: models/object_detection/tensorflow/ssd-mobilenet/inference/__init__.py
        - destination: models/object_detection/tensorflow/ssd-mobilenet/inference/coco_detection_evaluator.py
          source: models/object_detection/tensorflow/ssd-mobilenet/inference/coco_detection_evaluator.py
        - destination: models/object_detection/tensorflow/ssd-mobilenet/inference/coco_label_map.py
          source: models/object_detection/tensorflow/ssd-mobilenet/inference/coco_label_map.py
        - destination: models/object_detection/tensorflow/ssd-mobilenet/inference/coco_tools.py
          source: models/object_detection/tensorflow/ssd-mobilenet/inference/coco_tools.py
        - destination: models/object_detection/tensorflow/ssd-mobilenet/inference/ssdmobilenet_preprocess.pb
          source: models/object_detection/tensorflow/ssd-mobilenet/inference/ssdmobilenet_preprocess.pb
        - destination: models/common
          source: models/common
        - destination: models/object_detection/tensorflow/ssd-mobilenet/inference/
          source: models/object_detection/tensorflow/ssd-mobilenet/inference/
        - destination: models/object_detection/tensorflow/ssd-mobilenet
          source: models/object_detection/tensorflow/ssd-mobilenet
        - destination: quickstart/common
          source: quickstart/common
        - destination: quickstart
          source: quickstart/object_detection/tensorflow/ssd-mobilenet/inference/gpu/
      wrapper_package_files:
        - source: quickstart/object_detection/tensorflow/ssd-mobilenet/inference/gpu/build.sh
          destination: build.sh
        - source: dockerfiles/gpu_model_containers/tf-flex-series-ssd-mobilenet-inference.Dockerfile
          destination: tf-flex-series-ssd-mobilenet-inference.Dockerfile
        - source: output/tf-flex-series-ssd-mobilenet-inference.tar.gz
          destination: model_packages/tf-flex-series-ssd-mobilenet-inference.tar.gz
        - source: ""
          destination: info.txt
        - source: third_party
          destination: licenses/third_party
        - source: LICENSE
          destination: licenses/LICENSE
      partials:
        - numactl
        - python-build
        - object_detection/pip_installs
        - model_package
        - entrypoint
