releases:
  versioned:
    tag_specs:
    - '{tensorflow-itex-max-series-base-public}{tf-max-series-bert-large-training}'
slice_sets:
  tf-max-series-bert-large-training:
  - add_to_name: -tf-max-series-bert-large-training
    dockerfile_exclusive_name: -bert-large-training
    args:
    - PACKAGE_NAME=tf-max-series-bert-large-training
    dockerfile_subdirectory: gpu_model_containers
    downloads: []
    files:
    - destination: benchmarks/common
      source: benchmarks/common
    - destination: benchmarks/language_modeling/tensorflow/bert_large/README.md
      source: benchmarks/language_modeling/tensorflow/bert_large/README.md
    - destination: benchmarks/__init__.py
      source: benchmarks/__init__.py
    - destination: benchmarks/language_modeling/__init__.py
      source: benchmarks/language_modeling/__init__.py
    - destination: benchmarks/language_modeling/tensorflow/__init__.py
      source: benchmarks/language_modeling/tensorflow/__init__.py
    - destination: benchmarks/language_modeling/tensorflow/bert_large/__init__.py
      source: benchmarks/language_modeling/tensorflow/bert_large/__init__.py
    - destination: benchmarks/language_modeling/tensorflow/bert_large/training
      source: benchmarks/language_modeling/tensorflow/bert_large/training
    - destination: benchmarks/launch_benchmark.py
      source: benchmarks/launch_benchmark.py
    - destination: models/common
      source: models/common
    - destination: models/language_modeling/tensorflow/bert_large/training
      source: models/language_modeling/tensorflow/bert_large/training
    - destination: quickstart/common
      source: quickstart/common
    - destination: quickstart
      source: quickstart/language_modeling/tensorflow/bert_large/training/gpu
    - destination: quickstart/language_modeling/tensorflow/bert_large/training/gpu/generate_pretraining_data.sh
      source: quickstart/language_modeling/tensorflow/bert_large/training/gpu/generate_pretraining_data.sh
    - source: quickstart/language_modeling/tensorflow/bert_large/training/gpu/README.md
      destination: README.md
    - source: third_party
      destination: licenses/third_party
    - source: LICENSE
      destination: licenses/LICENSE
    wrapper_package_files:
    - source: quickstart/language_modeling/tensorflow/bert_large/training/gpu/bfloat16_training.sh
      destination: bfloat16_training.sh
    - source: quickstart/language_modeling/tensorflow/bert_large/training/gpu/bfloat16_training_hvd.sh
      destination: bfloat16_training_hvd.sh
    - source: quickstart/language_modeling/tensorflow/bert_large/training/gpu/build.sh
      destination: build.sh
    - source: dockerfiles/gpu_model_containers/tf-max-series-bert-large-training.Dockerfile
      destination: tf-max-series-bert-large-training.Dockerfile
    - source: output/tf-max-series-bert-large-training.tar.gz
      destination: model_packages/tf-max-series-bert-large-training.tar.gz
    - source: ""
      destination: info.txt
    - source: third_party
      destination: licenses/third_party
    - source: LICENSE
      destination: licenses/LICENSE  
    partials:
    - intel-mpi-ccl
    - model_package
    - horovod-patch
    - entrypoint
