releases:
  versioned:
    tag_specs:
    - '{_TAG_PREFIX}{intel-tf}{language-translation}{transformer-lt-official-inference}'
slice_sets:
  transformer-lt-official-inference:
  - add_to_name: -transformer-lt-official-inference
    args:
    - PACKAGE_NAME=transformer-lt-official-inference
    dockerfile_subdirectory: model_containers
    downloads:
    - source: https://storage.googleapis.com/intel-optimized-tensorflow/models/v1_6/transformer_lt_official_fp32_pretrained_model.tar.gz
      destination: transformer_lt_official_fp32_pretrained_model.tar.gz
    files:
    - destination: benchmarks/common
      source: benchmarks/common
    - destination: benchmarks/language_translation/__init__.py
      source: benchmarks/language_translation/__init__.py
    - destination: benchmarks/language_translation/tensorflow/__init__.py
      source: benchmarks/language_translation/tensorflow/__init__.py
    - destination: benchmarks/language_translation/tensorflow/transformer_lt_official/__init__.py
      source: benchmarks/language_translation/tensorflow/transformer_lt_official/__init__.py
    - destination: benchmarks/language_translation/tensorflow/transformer_lt_official/inference/__init__.py
      source: benchmarks/language_translation/tensorflow/transformer_lt_official/inference/__init__.py
    - destination: benchmarks/language_translation/tensorflow/transformer_lt_official/inference
      source: benchmarks/language_translation/tensorflow/transformer_lt_official/inference
    - destination: benchmarks/launch_benchmark.py
      source: benchmarks/launch_benchmark.py
    - destination: models/common
      source: models/common
    - destination: models/language_translation/tensorflow/transformer_lt_official/inference
      source: models/language_translation/tensorflow/transformer_lt_official/inference
    - destination: quickstart/common
      source: quickstart/common
    - destination: quickstart
      source: quickstart/language_translation/tensorflow/transformer_lt_official/inference/cpu
    partials:
    - model_package
    - language_translation/transformer_lt_pip_installs
    documentation:
      - name: README.md
        uri: models/quickstart/language_translation/tensorflow/transformer_lt_official/inference/cpu
        text_replace:
          <mode>: inference
          <model name>: Transformer LT Official
          <use case>: language_translation
          <docker image>: intel/language-translation:tf-latest-transformer-lt-official-inference
        docs:
        - name: Title
          uri: models/quickstart/language_translation/tensorflow/transformer_lt_official/inference/cpu/.docs/title.md
        - name: Description
          uri: models/quickstart/language_translation/tensorflow/transformer_lt_official/inference/cpu/.docs/description.md
        - name: Datasets
          uri: models/quickstart/language_translation/tensorflow/transformer_lt_official/inference/cpu/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/language_translation/tensorflow/transformer_lt_official/inference/cpu/.docs/quickstart.md
        - name: Docker
          uri: models/quickstart/language_translation/tensorflow/transformer_lt_official/inference/cpu/.docs/docker.md
        - name: Advanced Options
          uri: models/quickstart/language_translation/tensorflow/transformer_lt_official/inference/cpu/fp32/.docs/advancedoptions.md
        - name: License link
          uri: models/quickstart/language_translation/tensorflow/transformer_lt_official/inference/cpu/fp32/.docs/license.md
      - name: README.md
        uri: models/benchmarks/language_translation/tensorflow/transformer_lt_official/inference
        text_replace:
          <mode>: inference
          <model name>: Transformer LT Official
          <fp32 precision>: FP32
          <fp32 advanced readme link>: fp32/Advanced.md
          <use case>: language_translation
          <workload container url>: https://software.intel.com/content/www/us/en/develop/articles/containers/transformer-lt-official-fp32-inference-tensorflow-container.html
        docs:
        - name: Title
          uri: models/quickstart/language_translation/tensorflow/transformer_lt_official/inference/cpu/.docs/title.md
        - name: Description
          uri: models/quickstart/language_translation/tensorflow/transformer_lt_official/inference/cpu/.docs/description.md
        - name: Datasets
          uri: models/quickstart/language_translation/tensorflow/transformer_lt_official/inference/cpu/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/language_translation/tensorflow/transformer_lt_official/inference/cpu/.docs/quickstart.md
        - name: Bare Metal
          uri: models/quickstart/language_translation/tensorflow/transformer_lt_official/inference/cpu/.docs/baremetal.md
        - name: Resources
          uri: models/quickstart/common/.docs/resources_with_portal_link.md
      - docs:
        - name: Title
          uri: models/quickstart/common/.docs/advanced/title.md
        - name: Description
          uri: models/quickstart/common/.docs/advanced/description.md
        - name: Setup
          uri: models/quickstart/common/.docs/advanced/setup.md
        - name: Docker arg
          uri: models/quickstart/common/.docs/advanced/docker_arg.md
        - name: Launch benchmark instructions
          uri: models/benchmarks/language_translation/tensorflow/transformer_lt_official/inference/fp32/.docs/advanced/launch_benchmark_instructions.md
        name: Advanced.md
        text_replace:
          <mode>: inference
          <model name>: Transformer LT Official
          <precision>: FP32
          <use case>: language_translation
          <docker image>: intel/intel-optimized-tensorflow:latest
        uri: models/benchmarks/language_translation/tensorflow/transformer_lt_official/inference/fp32
