bs064-s1-fp16-yolov5m:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-object-detection-pytorch-flex-gpu-yolov5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  cap_add: SYS_NICE
  env:
    BATCH_SIZE: '64'
    STREAMS: '1'
    MODEL_NAME: 'yolov5m'
    NUM_INPUTS: '1'
    MAX_TEST_DURATION: '60'
    MIN_TEST_DURATION: '60'
    DUMMY: 'yes'
    PRECISION: 'fp16'
    JIT: 'trace'
    OUTPUT_DIR: '/tmp'
    http_proxy: '$http_proxy'
    https_proxy: '$https_proxy'
    PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: 'python'  
  volumes:
    - src: /tmp
      dst: /tmp
bs064-s4-fp16-yolov5m:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-object-detection-pytorch-flex-gpu-yolov5-inference
  cmd: bash run_model.sh 
  ipc: host
  device: /dev/dri
  cap_add: SYS_NICE
  env:
    BATCH_SIZE: '64'
    STREAMS: '4'
    MODEL_NAME: 'yolov5m'
    NUM_INPUTS: '64'
    MAX_TEST_DURATION: '60'
    MIN_TEST_DURATION: '60'
    DUMMY: 'yes'
    PRECISION: 'fp16'
    JIT: 'trace'
    OUTPUT_DIR: '/tmp'
    http_proxy: '$http_proxy'
    https_proxy: '$https_proxy'
    PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: 'python'
  volumes:
    - src: /tmp
      dst: /tmp
