kind: ConfigMap
apiVersion: v1
metadata:
  name: wide-deep-large-ds-fp32-training # {"$openapi":"MODEL_NAME"}
data:
  CHECKPOINT_DIR: /pvc/root/wide-deep-large-ds-fp32-training/checkpoints # {"$openapi":"CHECKPOINT_PATH"}
  DATASET_DIR: /datasets # {"$openapi":"DATASET_DIR"}
  FS_ID: "0" # {"$openapi":"FS_ID_VALUE"}
  GROUP_ID: "0" # {"$openapi":"GROUP_ID_VALUE"}
  GROUP_NAME: root # {"$openapi":"GROUP_NAME"}
  LD_LIBRARY_PATH: /usr/local/lib:/usr/local/lib/mpirun:$LD_LIBRARY_PATH
  MODEL_DIR: /workspace/wide-deep-large-ds-fp32-training # {"$openapi":"MODEL_DIR"} 
  OUTPUT_DIR: /pvc/root/wide-deep-large-ds-fp32-training/output # {"$openapi":"OUTPUT_PATH"}
  PYTHONPATH: /workspace/wide-deep-large-ds-fp32-training/models/recommendation/tensorflow/wide_deep_large_ds/training:$PYTHONPATH # {"$openapi":"PYTHONPATH"}
  TARGET_ACCURACY: "0.74" # {"$openapi":"TARGET_ACCURACY_VALUE"}
  USER_ID: "0" # {"$openapi":"USER_ID_VALUE"}
  USER_NAME: root # {"$openapi":"USER_NAME"}
