kind: ConfigMap
apiVersion: v1
metadata:
  name: resnet50v1-5-fp32-training # {"$openapi":"MODEL_NAME"}
data:
  DATASET_DIR: /datasets # {"$openapi":"DATASET_DIR"}
  FS_ID: "0" # {"$openapi":"FS_ID_VALUE"}
  GROUP_ID: "0" # {"$openapi":"GROUP_ID_VALUE"}
  GROUP_NAME: root # {"$openapi":"GROUP_NAME"}
  LD_LIBRARY_PATH: /usr/local/lib:/usr/local/lib/mpirun:$LD_LIBRARY_PATH
  MODEL_DIR: /workspace/resnet50v1-5-fp32-training # {"$openapi":"MODEL_DIR"} 
  OUTPUT_DIR: /pvc/root/resnet50v1-5-fp32-training/output # {"$openapi":"OUTPUT_PATH"}
  PYTHONPATH: /workspace/resnet50v1-5-fp32-training/models/image_recognition/tensorflow/resnet50v1_5/training:$PYTHONPATH # {"$openapi":"PYTHONPATH"}
  USER_ID: "0" # {"$openapi":"USER_ID_VALUE"}
  USER_NAME: root # {"$openapi":"USER_NAME"}
