apiVersion: v1
kind: Pod
metadata:
  name: rfcn-fp32-inference # {"$openapi":"MODEL_NAME"}
spec:
  serviceAccountName: rfcn-fp32-inference # {"$openapi":"MODEL_NAME"}
  securityContext:
    runAsUser: 0 # {"$openapi":"USER_ID"}
    runAsGroup: 0 # {"$openapi":"GROUP_ID"}
    fsGroup: 0 # {"$openapi":"FS_ID"}
  containers:
  - name: serving
    image: docker.io/intel/object-detection:tf-2.3.0-imz-2.2.0-rfcn-fp32-inference # {"$openapi":"IMAGE"}
    workingDir: /workspace/rfcn-fp32-inference # {"$openapi":"MODEL_DIR"}
    command: # {"$openapi":"COMMAND"}
    - /workspace/rfcn-fp32-inference/quickstart/fp32_inference.sh # {"$openapi":"COMMAND"}
    envFrom:
    - configMapRef:
        name: rfcn-fp32-inference # {"$openapi":"MODEL_NAME"}
    volumeMounts:
    - name: datasets
      mountPath: /datasets # {"$openapi":"DATASET_DIR"}
      readOnly: true
    - name: pvc-path
      mountPath: /pvc # {"$openapi":"PVC_PATH"}
  volumes:
  - name: datasets
    hostPath:
      path: /datasets # {"$openapi":"DATASET_DIR"}
  - name: pvc-path
    persistentVolumeClaim:
      claimName: workdisk # {"$openapi":"PVC_NAME"}
  restartPolicy: OnFailure
