releases:
  versioned:
    tag_specs:
    - '{_TAG_PREFIX}{intel-tf}{image-recognition}{mobilenet-v1-fp32-inference}'
slice_sets:
  mobilenet-v1-fp32-inference:
  - add_to_name: -mobilenet-v1-fp32-inference
    args:
    - PACKAGE_NAME=mobilenet-v1-fp32-inference
    dockerfile_subdirectory: model_containers
    downloads:
    - destination: mobilenet_v1_1.0_224_frozen.pb
      source: https://storage.googleapis.com/intel-optimized-tensorflow/models/v1_6/mobilenet_v1_1.0_224_frozen.pb
    files:
    - destination: benchmarks/common
      source: benchmarks/common
    - destination: benchmarks/image_recognition/__init__.py
      source: benchmarks/image_recognition/__init__.py
    - destination: benchmarks/image_recognition/tensorflow/__init__.py
      source: benchmarks/image_recognition/tensorflow/__init__.py
    - destination: benchmarks/image_recognition/tensorflow/mobilenet_v1/README.md
      source: benchmarks/image_recognition/tensorflow/mobilenet_v1/README.md
    - destination: benchmarks/image_recognition/tensorflow/mobilenet_v1/__init__.py
      source: benchmarks/image_recognition/tensorflow/mobilenet_v1/__init__.py
    - destination: benchmarks/image_recognition/tensorflow/mobilenet_v1/inference/__init__.py
      source: benchmarks/image_recognition/tensorflow/mobilenet_v1/inference/__init__.py
    - destination: benchmarks/image_recognition/tensorflow/mobilenet_v1/inference/fp32
      source: benchmarks/image_recognition/tensorflow/mobilenet_v1/inference/fp32
    - destination: benchmarks/launch_benchmark.py
      source: benchmarks/launch_benchmark.py
    - destination: models/common
      source: models/common
    - destination: models/image_recognition/tensorflow/mobilenet_v1/inference
      source: models/image_recognition/tensorflow/mobilenet_v1/inference
    - destination: quickstart/common
      source: quickstart/common
    - destination: quickstart
      source: quickstart/image_recognition/tensorflow/mobilenet_v1/inference/cpu/fp32
    partials:
    - model_package
    - entrypoint
    documentation:
      - name: README.md
        uri: models/quickstart/image_recognition/tensorflow/mobilenet_v1/inference/cpu/fp32
        text_replace:
          <model name>: MobileNet V1
          <precision>: FP32
          <mode>: inference
          <use case>: image_recognition
          <package url>: https://storage.googleapis.com/intel-optimized-tensorflow/models/v2_5_0/mobilenet-v1-fp32-inference.tar.gz
          <package name>: mobilenet-v1-fp32-inference.tar.gz
          <package dir>: mobilenet-v1-fp32-inference
          <docker image>: intel/image-recognition:tf-latest-mobilenet-v1-fp32-inference
        docs:
        - name: Title
          uri: models/quickstart/image_recognition/tensorflow/mobilenet_v1/inference/cpu/fp32/.docs/title.md
        - name: Description
          uri: models/quickstart/image_recognition/tensorflow/mobilenet_v1/inference/cpu/fp32/.docs/description.md
        - name: Download link
          uri: models/quickstart/image_recognition/tensorflow/mobilenet_v1/inference/cpu/fp32/.docs/download.md
        - name: Quick Start Scripts
          uri: models/quickstart/image_recognition/tensorflow/mobilenet_v1/inference/cpu/fp32/.docs/quickstart.md
        - name: Bare Metal
          uri: models/quickstart/image_recognition/tensorflow/mobilenet_v1/inference/cpu/fp32/.docs/baremetal.md
        - name: Docker
          uri: models/quickstart/image_recognition/tensorflow/mobilenet_v1/inference/cpu/fp32/.docs/docker.md
        - name: Advanced Options
          uri: models/quickstart/image_recognition/tensorflow/mobilenet_v1/inference/cpu/fp32/.docs/advancedoptions.md
        - name: License link
          uri: models/quickstart/image_recognition/tensorflow/mobilenet_v1/inference/cpu/fp32/.docs/license.md
