releases:
  versioned:
    tag_specs:
    - '{ubuntu}{intel-python}{pytorch-conda}{ipex-conda}{torch_ccl-conda}{dlrm-bfloat16-training}'
slice_sets:
  pytorch-conda:
  - add_to_name: "pytorch"
    partials:
    - pytorch/pytorch-conda
    tests:
    - pytorch/import-torch.sh 
  ipex-conda:
  - add_to_name: ""
    partials:
    - pytorch/ipex-conda
    tests:
    - pytorch/import-ipex.sh
  torch_ccl-conda:
  - add_to_name: ""
    args:
    - PYTHON_VERSION=3.7
    partials:
    - pytorch/torchccl-conda
    tests:
    - pytorch/import-torchccl.sh
  dlrm-bfloat16-training:
  - add_to_name: -dlrm-bfloat16-training
    args:
    - PACKAGE_NAME=dlrm-bfloat16-training
    dockerfile_subdirectory: pytorch 
    documentation:
      - docs:
        - name: Title
          uri: models/quickstart/recommendation/pytorch/dlrm/training/cpu/bfloat16/.docs/title.md
        - name: Description
          uri: models/quickstart/recommendation/pytorch/dlrm/training/cpu/bfloat16/.docs/description.md
        - name: Datasets
          uri: models/quickstart/recommendation/pytorch/dlrm/training/cpu/bfloat16/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/recommendation/pytorch/dlrm/training/cpu/bfloat16/.docs/quickstart.md
        - name: Bare Metal
          uri: models/quickstart/recommendation/pytorch/dlrm/training/cpu/bfloat16/.docs/baremetal.md
        - name: Docker
          uri: models/quickstart/recommendation/pytorch/dlrm/training/cpu/bfloat16/.docs/docker.md
        - name: License
          uri: models/quickstart/recommendation/pytorch/dlrm/training/cpu/bfloat16/.docs/license.md
        name: README.md
        text_replace:
          <docker image>: ''
          <mode>: training
          <model name>: Dlrm
          <package dir>: dlrm-bfloat16-training
          <package name>: dlrm-bfloat16-training.tar.gz
          <package url>: 'https://storage.googleapis.com/intel-optimized-tensorflow/models/v2_7_0/dlrm-bfloat16-training.tar.gz'
          <precision>: bfloat16
          <use case>: recommendation
        uri: models/quickstart/recommendation/pytorch/dlrm/training/cpu/bfloat16
    downloads: []
    files:
    - destination: models/recommendation/pytorch/dlrm/training/bfloat16
      source: models/recommendation/pytorch/dlrm/training/bfloat16
    - destination: quickstart
      source: quickstart/recommendation/pytorch/dlrm/training/cpu/bfloat16
    partials:
    - recommendation/dlrm
    - model_package
    - entrypoint
