releases:
  versioned:
    tag_specs:
    - '{pytorch}{pytorch-resnet50-bfloat16-inference}'
slice_sets:
  pytorch-resnet50-bfloat16-inference:
  - add_to_name: -resnet50-bfloat16-inference
    args:
    - PYTORCH_TAG=1.5.0-rc3-ipex-latest
    - PACKAGE_NAME=pytorch-resnet50-bfloat16-inference
    dockerfile_subdirectory: pytorch
    documentation:
      - docs:
        - name: Title
          uri: models/quickstart/image_recognition/pytorch/resnet50/inference/cpu/bfloat16/.docs/title.md
        - name: Description
          uri: models/quickstart/image_recognition/pytorch/resnet50/inference/cpu/bfloat16/.docs/description.md
        - name: Download link
          uri: models/quickstart/image_recognition/pytorch/resnet50/inference/cpu/bfloat16/.docs/download.md
        - name: Datasets
          uri: models/quickstart/image_recognition/pytorch/resnet50/inference/cpu/bfloat16/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/image_recognition/pytorch/resnet50/inference/cpu/bfloat16/.docs/quickstart.md
        - name: Bare Metal
          uri: models/quickstart/image_recognition/pytorch/resnet50/inference/cpu/bfloat16/.docs/baremetal.md
        - name: Docker
          uri: models/quickstart/image_recognition/pytorch/resnet50/inference/cpu/bfloat16/.docs/docker.md
        - name: License
          uri: models/quickstart/image_recognition/pytorch/resnet50/inference/cpu/bfloat16/.docs/license.md
        name: README.md
        text_replace:
          <docker image>: 'intel/image-recognition:pytorch-1.5.0-rc3-resnet50-bfloat16-inference'
          <mode>: inference
          <model name>: ResNet50
          <package dir>: pytorch-resnet50-bfloat16-inference
          <package name>: pytorch-resnet50-bfloat16-inference.tar.gz
          <package url>: 'https://storage.googleapis.com/intel-optimized-tensorflow/models/v2_7_0/pytorch-resnet50-bfloat16-inference.tar.gz'
          <precision>: BFloat16
          <use case>: image_recognition
        uri: models/quickstart/image_recognition/pytorch/resnet50/inference/cpu/bfloat16
    downloads: []
    files:
    - destination: models/image_recognition/pytorch/common
      source: models/image_recognition/pytorch/common
    - destination: quickstart/common
      source: quickstart/common
    - destination: quickstart
      source: quickstart/image_recognition/pytorch/resnet50/inference/cpu/bfloat16
    partials:
    - model_package
    - entrypoint
