releases:
  versioned:
    tag_specs:
    - '{pytorch-ipex-max-series-base-public}{pytorch-max-series-bert-large-training}'
slice_sets:
  pytorch-max-series-bert-large-training:
  - add_to_name: pytorch-max-series-bert-large-training
    dockerfile_exclusive_name: -bert-large-training
    args:
    - PACKAGE_NAME=pytorch-max-series-bert-large-training
    dockerfile_subdirectory: gpu_model_containers
    downloads: []
    files:
    - source: quickstart/language_modeling/pytorch/bert_large/training/gpu/README.md
      destination: README.md
    - destination: models/language_modeling/pytorch/bert_large/training/gpu
      source: models/language_modeling/pytorch/bert_large/training/gpu
    - destination: quickstart/bf16_training_plain_format.sh
      source: quickstart/language_modeling/pytorch/bert_large/training/gpu/bf16_training_plain_format.sh
    - destination: quickstart/ddp_bf16_training_plain_format.sh
      source: quickstart/language_modeling/pytorch/bert_large/training/gpu/ddp_bf16_training_plain_format.sh
    - source: quickstart/common/pytorch/gpu/setvars.sh
      destination: quickstart/setvars.sh
    wrapper_package_files:
     - source: quickstart/language_modeling/pytorch/bert_large/training/gpu/build.sh
       destination: build.sh
     - source: dockerfiles/gpu_model_containers/pytorch-max-series-bert-large-training.Dockerfile
       destination: pytorch-max-series-bert-large-training.Dockerfile
     - source: output/pytorch-max-series-bert-large-training.tar.gz
       destination: model_packages/pytorch-max-series-bert-large-training.tar.gz
     - source: ""
       destination: info.txt
     - source: third_party
       destination: licenses/third_party
     - source: LICENSE
       destination: licenses/LICENSE
    partials:
    - intel-mpi-oneccl
    - model_package
    - pytorch/bert-training-installs
    - entrypoint
