kind: ConfigMap
apiVersion: v1
metadata:
  name: bert-large-fp32-training # {"$openapi":"MODEL_NAME"}
data:
  BERT_BASE_DIR: bert_official/MRPC/uncased_L-12_H-768_A-12 # {"$openapi":"BERT_BASE_DIR"}
  DATASET_DIR: /datasets # {"$openapi":"DATASET_DIR"}
  FS_ID: "0" # {"$openapi":"FS_ID_VALUE"}
  GLUE_DIR: bert_official # {"$openapi":"GLUE_DIR"}
  GROUP_ID: "0" # {"$openapi":"GROUP_ID_VALUE"}
  GROUP_NAME: root # {"$openapi":"GROUP_NAME"}
  LD_LIBRARY_PATH: /usr/local/lib:/usr/local/lib/mpirun:$LD_LIBRARY_PATH
  MODEL_DIR: /workspace/bert-large-fp32-training # {"$openapi":"MODEL_DIR"} 
  OUTPUT_DIR: /nfs/root/bert-large-fp32-training/output # {"$openapi":"OUTPUT_PATH"}
  PYTHONPATH: /workspace/bert-large-fp32-training/models/language_modeling/tensorflow/bert_large/training:$PYTHONPATH # {"$openapi":"PYTHONPATH"}
  USER_ID: "0" # {"$openapi":"USER_ID_VALUE"}
  USER_NAME: root # {"$openapi":"USER_NAME"}
