apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: rfcn-fp32-inference-wf # {"$openapi":"WORKFLOW_NAME"}
spec:
  entrypoint: rfcn-fp32-inference # {"$openapi":"MODEL_NAME"}
  templates:
  - name: rfcn-fp32-inference # {"$openapi":"MODEL_NAME"}
    steps:
    - - name: preprocess-coco
        template: preprocess-coco
    - - name: rfcn-fp32-accuracy
        template: rfcn-fp32-accuracy
  - name: preprocess-coco
    securityContext:
      runAsUser: 0 # {"$openapi":"USER_ID"}
      runAsGroup: 0 # {"$openapi":"GROUP_ID"}
      fsGroup: 0 # {"$openapi":"FS_ID"}
    container:
      image: docker.io/intel/object-detection:tf-1.15.2-imz-2.2.0-preprocess-coco-val # {"$openapi":"PREPROCESS_IMAGE"}
      command: # {"$openapi":"PREPROCESS_COMMAND"}
      - /workspace/preprocess-coco-val/scripts/preprocess_coco_val.sh # {"$openapi":"PREPROCESS_COMMAND"}
      envFrom:
      - configMapRef:
          name: rfcn-fp32-inference # {"$openapi":"MODEL_NAME"}
      volumeMounts:
      - name: pvc-path
        mountPath: /pvc # {"$openapi":"PVC_PATH"}
      - name: coco-raw-data
        mountPath: /datasets # {"$openapi":"DATASET_DIR"}
        readOnly: true
      - name: mlops-scripts
        mountPath: /workspace/preprocess-coco-val/scripts/preprocess_coco_val.sh # {"$openapi":"PREPROCESS_COMMAND"}
        subPath: preprocess_coco_val.sh # {"$openapi":"PREPROCESS_SCRIPT"}
    volumes:
    - name: coco-raw-data
      hostPath:
        path: /datasets # {"$openapi":"DATASET_DIR"}
    - name: pvc-path
      persistentVolumeClaim:
        claimName: workdisk # {"$openapi":"PVC_NAME"}
    - name: mlops-scripts
      configMap:
        name: mlops-scripts-rfcn-fp32-inference # {"$openapi":"MODEL_CONFIGMAP_NAME"}
        defaultMode: 0770
        items:
        - key: preprocess_coco_val.sh # {"$openapi":"PREPROCESS_SCRIPT"}
          path: preprocess_coco_val.sh # {"$openapi":"PREPROCESS_SCRIPT"}
  - name: rfcn-fp32-accuracy
    securityContext:
      runAsUser: 0 # {"$openapi":"USER_ID"}
      runAsGroup: 0 # {"$openapi":"GROUP_ID"}
      fsGroup: 0 # {"$openapi":"FS_ID"}
    container:
      image: docker.io/intel/object-detection:tf-2.3.0-imz-2.2.0-rfcn-fp32-inference # {"$openapi":"IMAGE"}
      imagePullPolicy: Always
      command: # {"$openapi":"MODEL_COMMAND"}
      - /workspace/rfcn-fp32-inference/quickstart/fp32_accuracy.sh # {"$openapi":"MODEL_COMMAND"}
      envFrom:
      - configMapRef:
          name: rfcn-fp32-inference # {"$openapi":"MODEL_NAME"}
      volumeMounts:
      - name: pvc-path
        mountPath: /pvc # {"$openapi":"PVC_PATH"}
      - name: mlops-scripts
        mountPath: /workspace/rfcn-fp32-inference/quickstart/fp32_accuracy.sh # {"$openapi":"MODEL_COMMAND"}
        subPath: fp32_accuracy.sh # {"$openapi":"MODEL_SCRIPT"}
    volumes:
    - name: pvc-path
      persistentVolumeClaim:
        claimName: workdisk # {"$openapi":"PVC_NAME"}
    - name: mlops-scripts
      configMap:
        name: rfcn-fp32-inference # {"$openapi":"MODEL_NAME"}
        defaultMode: 0770
        items:
        - key: fp32_accuracy.sh # {"$openapi":"MODEL_SCRIPT"}
          path: fp32_accuracy.sh # {"$openapi":"MODEL_SCRIPT"}
