fp16-flex170-10000-batch-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-wide-deep-large-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env: 
    BATCH_SIZE: '10000'
    DATASET_PATH: /local_dateset/datasets/wide_deep_large/data/eval_preprocessed_eval.tfrecords
    PB_FILE_PATH: /local_dateset/datasets/wide_deep_large/wide_deep_fp16_pretrained_model.pb
    GPU_TYPE: flex_170
    OUTPUT_DIR: /tmp
  volumes:
    - src: /local_dateset/datasets/wide_deep_large/data/eval_preprocessed_eval.tfrecords
      dst: /local_dateset/datasets/wide_deep_large/data/eval_preprocessed_eval.tfrecords
    - src: /local_dateset/datasets/wide_deep_large/wide_deep_fp16_pretrained_model.pb
      dst: /local_dateset/datasets/wide_deep_large/wide_deep_fp16_pretrained_model.pb
fp16-flex140-10000-batch-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-wide-deep-large-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  cap_add: SYS_NICE
  env: 
    BATCH_SIZE: '10000'
    DATASET_PATH: /local_dateset/datasets/wide_deep_large/data/eval_preprocessed_eval.tfrecords
    PB_FILE_PATH: /local_dateset/datasets/wide_deep_large/wide_deep_fp16_pretrained_model.pb
    GPU_TYPE: flex_140
    OUTPUT_DIR: /tmp
  volumes:
    - src: /local_dateset/datasets/wide_deep_large/data/eval_preprocessed_eval.tfrecords
      dst: /local_dateset/datasets/wide_deep_large/data/eval_preprocessed_eval.tfrecords
    - src: /local_dateset/datasets/wide_deep_large/wide_deep_fp16_pretrained_model.pb
      dst: /local_dateset/datasets/wide_deep_large/wide_deep_fp16_pretrained_model.pb
