varReference:
- kind: PersistentVolume
  path: spec/hostPath/path
- kind: Pod
  path: spec/containers/image
- kind: Pod
  path: spec/containers/workingDir
- kind: Pod
  path: spec/containers/command
- kind: Pod
  path: spec/containers/volumeMounts/mountPath
