releases:
  versioned:
    tag_specs:
    - '{spr-ssd-resnet34-inference}'
slice_sets:
  spr-ssd-resnet34-inference:
    - add_to_name: tf-spr-ssd-resnet34-inference
      dockerfile_subdirectory: tensorflow-spr
      args:
        - PACKAGE_NAME=tf-spr-ssd-resnet34-inference
        - TENSORFLOW_IMAGE=model-zoo
        - TENSORFLOW_TAG=tensorflow-spr
        - PY_VERSION=3.8
        - CODE_DIR=/workspace/tf_models
        - TF_MODELS_BRANCH=f505cecde2d8ebf6fe15f40fb8bc350b2b1ed5dc
        - TF_BENCHMARKS_DIR=/workspace/ssd-resnet-benchmarks
        - TF_BENCHMARKS_BRANCH=509b9d288937216ca7069f31cfb22aaa7db6a4a7
      partials:
        - tensorflow/tensorflow-base
        - common
        - python-build
        - tensorflow/model-source
        - object_detection/pip_installs
        - object_detection/protoc
        - libgl
        - opencv
        - tensorflow-addons-0.18.0
        - model_package
        - entrypoint
        - tensorflow/benchmarks-source
      files:
        - destination: benchmarks/common
          source: benchmarks/common
        - destination: benchmarks/object_detection/__init__.py
          source: benchmarks/object_detection/__init__.py
        - destination: benchmarks/object_detection/tensorflow/__init__.py
          source: benchmarks/object_detection/tensorflow/__init__.py
        - destination: benchmarks/object_detection/tensorflow/ssd-resnet34/__init__.py
          source: benchmarks/object_detection/tensorflow/ssd-resnet34/__init__.py
        - destination: benchmarks/object_detection/tensorflow/ssd-resnet34/inference/__init__.py
          source: benchmarks/object_detection/tensorflow/ssd-resnet34/inference/__init__.py
        - destination: benchmarks/object_detection/tensorflow/ssd-resnet34/inference
          source: benchmarks/object_detection/tensorflow/ssd-resnet34/inference
        - destination: benchmarks/launch_benchmark.py
          source: benchmarks/launch_benchmark.py
        - source: quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/multi_instance_online_inference_1200.sh
          destination: quickstart/inference_realtime.sh
        - source: quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/multi_instance_batch_inference_1200.sh
          destination: quickstart/inference_throughput.sh
        - source: quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/accuracy_1200.sh
          destination: quickstart/accuracy.sh
        - destination: models/common
          source: models/common
        - destination: models/object_detection/tensorflow/ssd-resnet34/inference
          source: models/object_detection/tensorflow/ssd-resnet34/inference
        - destination: models/object_detection/tensorflow/ssd-resnet34/inference/__init__.py
          source: models/object_detection/tensorflow/ssd-resnet34/inference/__init__.py
        - destination: quickstart/common
          source: quickstart/common
      downloads:
        - source: https://storage.googleapis.com/intel-optimized-tensorflow/models/2_10_0/ssd_resnet34_fp32_1200x1200_pretrained_model.pb
          destination: pretrained_model/ssd_resnet34_fp32_1200x1200_pretrained_model.pb
        - source: https://storage.googleapis.com/intel-optimized-tensorflow/models/2_10_0/ssd_resnet34_int8_1200x1200_pretrained_model.pb
          destination: pretrained_model/ssd_resnet34_int8_1200x1200_pretrained_model.pb
      wrapper_package_files:
        - source: output/tf-spr-ssd-resnet34-inference.tar.gz
          destination: model_packages/tf-spr-ssd-resnet34-inference.tar.gz
        - source: quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/build.sh
          destination: build.sh
        - source: quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/run.sh
          destination: run.sh
        - source: dockerfiles/tensorflow-spr/tf-spr-ssd-resnet34-inference.Dockerfile
          destination: tf-spr-ssd-resnet34-inference.Dockerfile
        - source: LICENSE
          destination: licenses/LICENSE
        - source: third_party
          destination: licenses/third_party
        - source: quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/README_SPR.md
          destination: README.md
      documentation:
        - docs:
          - name: Title
            uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/.docs/title.md
          - name: Description
            uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/.docs/description.md
          - name: Model Package
            uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/.docs/wrapper_package.md
          - name: Quickstart
            uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/.docs/quickstart.md
          - name: Datasets
            uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/.docs/datasets.md
          - name: Container build
            uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/.docs/container_build.md
          - name: Docker
            uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/.docs/docker_spr.md
          - name: License
            uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu/.docs/license.md
          name: README_SPR.md
          text_replace:
            <model name>: SSD-ResNet34
            <mode>: inference
            <package name>: tf-spr-ssd-resnet34-inference.tar.gz
            <package dir>: tf-spr-ssd-resnet34-inference
            <docker image>: model-zoo:tf-spr-ssd-resnet34-inference
          uri: models/quickstart/object_detection/tensorflow/ssd-resnet34/inference/cpu
