170-fp16-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-segmentation-tf-flex-gpu-maskrcnn-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env:
    BATCH_SIZE: '16'
    PRECISION: float16
    GPU_TYPE: flex_170
    DATASET_DIR: /tf_dataset/dataset/coco_dataset/COCO2017_training_data/
    OUTPUT_DIR: /tmp
  volumes:
    - src: ${DATASET_DIR:-/tf_dataset/dataset/coco_dataset/COCO2017_training_data/}
      dst: /tf_dataset/dataset/coco_dataset/COCO2017_training_data/
    - src: /tmp
      dst: /tmp
140-online-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-segmentation-tf-flex-gpu-maskrcnn-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env:
    BATCH_SIZE: '1'
    PRECISION: float16
    GPU_TYPE: flex_140
    DATASET_DIR: /tf_dataset/dataset/coco_dataset/COCO2017_training_data/
    OUTPUT_DIR: /tmp
  volumes:
    - src: ${DATASET_DIR:-/tf_dataset/dataset/coco_dataset/COCO2017_training_data/}
      dst: /tf_dataset/dataset/coco_dataset/COCO2017_training_data/
    - src: /tmp
      dst: /tmp
